# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy the built Angular artifacts into the Nginx image
COPY dist/<your-angular-app-name> /usr/share/nginx/html

# Expose port 80 to allow external access
EXPOSE 80
