version: '3.7'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    networks:
      - my-movie-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://config-server:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - my-movie-network

  mysqldb:
    image: mysql:8.0.36
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dockerDB
    networks:
      - my-movie-network

  eureka-server:
    image: tejajagadeep/movie-app-eureka-server
    container_name: eureka-container
    build:
      context: eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-movie-network

  config-server:
    image: tejajagadeep/movie-app-config-server
    container_name: config-container
    build:
      context: config-server
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8888:8888"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
    links:
      - eureka-server

  authentication-service:
    image: tejajagadeep/movie-app-authentication-service
    container_name: authentication-container
    build:
      context: authentication-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/authDB?createDatabaseIfNotExist=true
      - kafka.ip.address=kafka:9092  # run "docker inspect kafka_image_id" to get ip address
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
      - spring.jpa.hibernate.ddl-auto=create
    ports:
      - "8090:8090"
    networks:
      - my-movie-network
    depends_on:
      - mysqldb
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin-server
      - mysqldb
      - zookeeper
      - kafka
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  userprofile-service:
    image: tejajagadeep/movie-app-userprofile-service
    container_name: userprofile-container
    build:
      context: userprofile-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/userprofileDB?createDatabaseIfNotExist=true
      - kafka.ip.address=kafka:9092
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
      - spring.jpa.hibernate.ddl-auto=create
    ports:
      - "8092:8092"
    networks:
      - my-movie-network
    depends_on:
      - mysqldb
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin-server
      - mysqldb
      - zookeeper
      - kafka
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8092/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  movie-service:
    image: tejajagadeep/movie-app-movie-service
    container_name: movie-container
    build:
      context: movie-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8081:8081"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin-server
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  wishlist-service:
    image: tejajagadeep/movie-app-wishlist-service
    container_name: wishlist-container
    build:
      context: wishlist-service
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8082:8082"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin-server
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  api-gateway:
    image: tejajagadeep/movie-app-api-gateway
    container_name: gateway-container
    build:
      context: api-gateway
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - management.zipkin.tracing.endpoint=http://zipkin-server:9411/api/v2/spans
    ports:
      - "8765:8765"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin-server
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      interval: 20s
      timeout: 10s
      retries: 10

  swagger-server:
    image: tejajagadeep/movie-app-swagger-server
    container_name: swagger-server
    build:
      context: swagger-server
      dockerfile: Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
    ports:
      - "8769:8769"
    networks:
      - my-movie-network


  zipkin-server:
    image: openzipkin/zipkin
    container_name: zipkin-container
    ports:
      - "9411:9411"
    networks:
      - my-movie-network

networks:
  my-movie-network:
    driver: bridge
