version: '3.7'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    networks:
      - my-movie-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://config-server:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
      - my-movie-network

  mysqldb:
    image: mysql
    container_name: mysql-container
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: dockerDB
    networks:
      - my-movie-network

  eureka-server:
    image: eureka-server
    container_name: eureka-container
    build:
      context: /eureka-server
      dockerfile: /Dockerfile
    ports:
      - "8761:8761"
    networks:
      - my-movie-network

  config-server:
    image: config-server
    container_name: config-container
    build:
      context: /config-server
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    ports:
      - "8888:8888"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
    links:
      - eureka-server

  authentication-service:
    image: authentication-service
    container_name: authentication-container
    build:
      context: /authentication-service
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/authDB?createDatabaseIfNotExist=true
      - kafka.ip.address=http://kafka:9092
      - spring.zipkin.base-url=http://zipkin:9411/zipkin/
    ports:
      - "8090:8090"
    networks:
      - my-movie-network
    depends_on:
      - mysqldb
      - eureka-server
      - config-server
    links:
      - eureka-server
      - mysqldb
      - config-server
      - zookeeper
      - kafka
      - zipkin

  userprofile-service:
    image: userprofile-service
    container_name: userprofile-container
    build:
      context: /userprofile-service
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/userprofileDB?createDatabaseIfNotExist=true
      - kafka.ip.address=http://kafka:9092
      - spring.zipkin.base-url=http://zipkin:9411/zipkin/
    ports:
      - "8092:8092"
    networks:
      - my-movie-network
    depends_on:
      - mysqldb
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin
      - mysqldb
      - zookeeper
      - kafka

  movie-service:
    image: movie-service
    container_name: movie-container
    build:
      context: /movie-service
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.zipkin.base-url=http://zipkin:9411/zipkin/
    ports:
      - "8081:8081"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin

  wishlist-service:
    image: wishlist-service
    container_name: wishlist-container
    build:
      context: /wishlist-service
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.zipkin.base-url=http://zipkin:9411/zipkin/
    ports:
      - "8082:8082"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin

  api-gateway:
    image: api-gateway
    container_name: gateway-container
    build:
      context: /api-gateway
      dockerfile: /Dockerfile
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.config.import=optional:configserver:http://config-server:8888/
      - spring.zipkin.base-url=http://zipkin:9411/zipkin/
    ports:
      - "9000:9000"
    networks:
      - my-movie-network
    depends_on:
      - eureka-server
      - config-server
    links:
      - eureka-server
      - config-server
      - zipkin


  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-container
    ports:
      - "9411:9411"
    networks:
      - my-movie-network

networks:
  my-movie-network:
    driver: bridge
