FROM openjdk:17-alpine
LABEL author="teja jagadeep"
WORKDIR usr/src
ADD /target/authentication-service-0.0.1-SNAPSHOT.jar /usr/src/authentication-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar", "authentication-service-0.0.1-SNAPSHOT.jar"]