FROM openjdk:17-alpine
LABEL author="teja jagadeep"
WORKDIR usr/src
ADD /target/eureka-server-0.0.1-SNAPSHOT.jar /usr/src/eureka-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar", "eureka-server-0.0.1-SNAPSHOT.jar"]