spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: USERPROFILE-SERVICE
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - name: Path
              args:
                pattern: /api/v1.0/private/userProfile/**
            - name: Path
              args:
                pattern: /api/v1.0/public/userProfile/**

        - id: MUSIC-SERVICE
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/api/v1.0/private/movie/**

        - id: WISHLIST-SERVICE
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/api/v1.0/private/wishlist/**

        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1.0/public/auth/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9090
