spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: USERPROFILE-SERVICE
          uri: lb://USERPROFILE-SERVICE
          predicates:
            - Path=/api/v1.0/userProfile/**
        - id: MUSIC-SERVICE
          uri: lb://MUSIC-SERVICE
          predicates:
            - Path=/api/v1.0/movie/**

        - id: WISHLIST-SERVICE
          uri: lb://WISHLIST-SERVICE
          predicates:
            - Path=/api/v1.0/wishlist/**

        - id: AUTHENTICATION-SERVICE
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1.0/auth/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 9090
  defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_api_gateway:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file spotify-backend/api-gateway/pom.xml


  build_authentication_service:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Authentication Service with Maven
        run: mvn -B package --file spotify-backend/authentication-service/pom.xml