FROM openjdk:17-alpine
WORKDIR usr/src
COPY /target/userprofile-service-0.0.1-SNAPSHOT.jar /usr/src/userprofile-service-0.0.1-SNAPSHOT.jar
ENTRYPOINT [ "java","-jar", "userprofile-service-0.0.1-SNAPSHOT.jar"]