name: Docker-Compose CI/CD Docker

on:
  push:
    branches:
      - main
    paths:
      - "assets/advanced/**"

jobs:
  build_docker_compose_container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/docker-compose-movie-container:latest assets/advanced
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/docker-compose-movie-container:latest
