# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI/CD with Maven and Docker on authentication-service

on:
  push:
    branches: ["main"]
    paths:
      - "movie-backend/authentication-service/**"
  pull_request:
    branches: ["main"]

jobs:
  build_authentication_service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Build Maven Authentication Service
        run: mvn -B package --file movie-backend/authentication-service/pom.xml
      - name: Build docker Authentication Service
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/movie-app-authentication-service:latest -f movie-backend/authentication-service/Dockerfile movie-backend/authentication-service
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/movie-app-authentication-service:latest
